### ISSUE TITLE
Typings install fails

### ISSUE THREAD

**Issue by zachallen** [samvloeberghs/protractor-gherkin-cucumberjs-angular2#1]
Performing an 'npm install' on a fresh copy of the project I get the following error:

typings ERR! message Unable to read typings for "jasmine". You should check the path is correct
typings ERR! caused by https://raw.githubusercontent.com/angular/DefinitelyTyped/4b36b94d5910aa8a4d20bdcd5bd1f9ae6ad18d3c/jasmine/jasmine.d.ts responded with 404, expected it to equal 200

**Comment by samvloeberghs** [comment]
Hi Zachallen,

I've been unwatching this project for a while.
I'll put some updates very soon as I'm working on a talk around this matter.

Keep you posted if still interested!

Grtz

**Comment by samvloeberghs** [comment]
Hi @zachallen project updated

**Comment by samvloeberghs** [comment]
Hi @zachallen project updated, can you please check if it's ok on your side now?

**Comment by pawelczak** [comment]
Hi @samvloeberghs, everything works correctly.
