### ISSUE TITLE
update to ng2 - rc6 when released

### ISSUE THREAD

**Issue by samvloeberghs** [samvloeberghs/protractor-gherkin-cucumberjs-angular2#16]

**Comment by DennisJaamann** [comment]
Should be RC7 already

**Comment by samvloeberghs** [comment]
a good approach would be to first update to rc6, to see what is changed compared to rc4.
Than do the upgrade to rc7. I'll create a new issue for RC7

**Comment by samvloeberghs** [comment]
closed due to https://github.com/samvloeberghs/protractor-gherkin-cucumberjs-angular2/pull/20
