### ISSUE TITLE
Debugging / SourceMap Support

### ISSUE THREAD

**Issue by pete2014** [samvloeberghs/protractor-gherkin-cucumberjs-angular2#17]
Hi,

I would like to debug the steps in VS Code Chrome Debug Plugin. This doesn't work now as there is no sourcemap support in the project at this time. Would you be able to advise what needs to be changed/added to allow debugging with breakpoints within the original typescript code.

Many Thanks

**Comment by samvloeberghs** [comment]
@pete2014 not sure how to do this yet. As I believe these steps are not running in the browser, but in the process instructing the browser.

**Comment by samvloeberghs** [comment]
cleaning up
