### ISSUE TITLE
npm run e2e fails

### ISSUE THREAD

**Issue by chrisse27** [samvloeberghs/protractor-gherkin-cucumberjs-angular2#32]
I followed your instructions from Readme.md.

However, npm run e2e failed complaining about duplicate definitions of Promise in the "es6-promise" type definitions. After I had removed this entry from the tsconfig everything worked like a charm.

**Comment by samvloeberghs** [comment]
thx for the headsup! I'll provide a fix 👍

**Comment by samvloeberghs** [comment]
fixed with: https://github.com/samvloeberghs/protractor-gherkin-cucumberjs-angular2/pull/33
can you verify @chrisse27 ?

**Comment by chrisse27** [comment]
@samvloeberghs Verified.
