### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by tecris** [samvloeberghs/protractor-gherkin-cucumberjs-angular2#4]
Hi, first of all many thanks for the demo project.

On a 'npm install' I get following error:
npm ERR! peerinvalid The package rxjs@5.0.0-beta.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular2@2.0.0-beta.13 wants rxjs@5.0.0-beta.2
npm ERR! peerinvalid Peer @angular/core@2.0.0-rc.1 wants rxjs@5.0.0-beta.6

**Comment by samvloeberghs** [comment]
I need to update to rc fast :)

**Comment by samvloeberghs** [comment]
@tecris, repo updated!
