### ISSUE TITLE
Missing TypeScript type definitions for 'source-map' & 'uglify-js'

### ISSUE THREAD

**Issue by KeithGillette** [samvloeberghs/protractor-gherkin-cucumberjs-angular2#43]
I was able to run the application with _npm start_ but unable to complete the end-to-end tests with _npm run e2e_, as protractor failed with:

```
E/launcher - Error: TSError: ⨯ Unable to compile TypeScript
Cannot find type definition file for 'source-map'. (2688)
Cannot find type definition file for 'uglify-js'. (2688)
```

I was able to correct the issue with the following additions to **package.json** and re-rerunning _npm install_:
```
  "devDependencies": {
    "@types/source-map": "0.5.0",
    "@types/uglify-js": "2.6.28",
}
```

Thanks for putting this sample project out!

**Comment by samvloeberghs** [comment]
@KeithGillette thx for this headsup!! Could you perhaps create a Pull request? I'd be happy to merge this :)

**Comment by samvloeberghs** [comment]
closed with https://github.com/samvloeberghs/protractor-gherkin-cucumberjs-angular2/pull/44
