### ISSUE TITLE
update to angular 2.4

### ISSUE THREAD

**Issue by samvloeberghs** [samvloeberghs/protractor-gherkin-cucumberjs-angular2#47]

**Comment by samvloeberghs** [comment]
@DennisJaamann do you perhaps have som  time for this? :)

**Comment by DennisJaamann** [comment]
Yeah for sure, will do this now

**Comment by samvloeberghs** [comment]
fixed by https://github.com/samvloeberghs/protractor-gherkin-cucumberjs-angular2/pull/49
