### ISSUE TITLE
Unable to compile typescript

### ISSUE THREAD

**Issue by thirumalai-kc** [samvloeberghs/protractor-gherkin-cucumberjs-angular2#53]
I'm getting the below error while running cucumber 'npm run e2e:cucumber'. I replicated the same setup as in your project but My application launched successfully after logged in but crashes after it start executing the first scenario step 'home.step.ts'. 

[10:25:05] I/direct - Using ChromeDriver directly...
[10:25:05] I/launcher - Running 1 instances of WebDriver
[10:25:10] E/launcher - Error: TSError: ⨯ Unable to compile TypeScript
e2e/home/home.steps.ts (11,7): Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning. (12
19)
e2e/home/home.steps.ts (16,13): Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning. (1
219)
e2e/home/home.steps.ts (22,13): Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning. (1
219)
e2e/home/home.steps.ts (28,13): Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning. (1
219)
    at getOutput (/node_modules/ts-node/src/index.ts:258:17)
    at /node_modules/ts-node/src/index.ts:267:16
    at Object.compile (/node_modules/ts-node/src/index.ts:403:17)
    at loader (/node_modules/ts-node/src/index.ts:289:33)
    at Object.require.extensions.(anonymous function) [as .ts] (/node_modules/ts-node/src/index.ts:306:14)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
[10:25:10] E/launcher - Process exited with error code 100

**Comment by samvloeberghs** [comment]
Please read the error..

**Comment by thirumalai-kc** [comment]
Yes I set the experimentalDecorators as in the below tsconfig.json. But still the issue exist. Please find the dependencies in package.json. I'm able to run e2e protractor without any issues but only the cucumber test is failing with the above error. Am I missing some dependencies?

tsconfig.json

{
  "compileOnSave": false,
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc-e2e",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ],
    "types": [
      "selenium-webdriver",
      "node",
      "cucumber",
      "jasmine"
    ]
  },
  "exclude": [
    "node_modules"
  ],
  "awesomeTypescriptLoaderOptions": {
    "resolveGlobs": true,
    "forkChecker": true
  }
}


Package.json

{
  "name": "scheduling-ui",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test --watch false",
    "e2e": "better-npm-run e2e:basic:local",
    "e2e:basic": "better-npm-run e2e:basic:local",
    "e2e:basic:local": "better-npm-run e2e:basic:local",
    "e2e:cucumber": "better-npm-run e2e:cucumber:local",
    "e2e:cucumber:local": "better-npm-run e2e:cucumber:local"
  },
  "betterScripts": {
    "e2e:basic:local": {
      "command": "protractor",
      "env": {
        "TEST_METHOD": "basic",
        "TEST_ENV": "local"
      }
    },
    "e2e:cucumber:local": {
      "command": "protractor",
      "env": {
        "TEST_METHOD": "cucumber",
        "TEST_ENV": "local"
      }
    }
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.1.2",
    "@angular/compiler": "2.1.2",
    "@angular/core": "2.1.2",
    "@angular/forms": "2.1.2",
    "@angular/http": "2.1.2",
    "@angular/platform-browser": "2.1.2",
    "@angular/platform-browser-dynamic": "2.1.2",
    "@angular/router": "3.0.0",
    "angular2-moment": "1.0.0-beta.6",
    "core-js": "2.4.1",
    "font-awesome": "4.6.3",
    "keycloak-js": "2.2.1",
    "moment": "2.15.1",
    "ng2-bootstrap": "1.1.5",
    "ng2-select-controls": "0.0.18",
    "primeng": "1.1.4",
    "primeui": "4.1.15",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "1.1.1",
    "zone.js": "0.6.23"
  },
  "devDependencies": {
    "@types/cucumber": "0.0.31",
    "@types/jasmine": "2.2.30",
    "@types/node": "6.0.38",
    "@types/webpack": "1.12.34",
    "angular-cli": "1.0.0-beta.19-3",
    "awesome-typescript-loader": "~2.2.1",
    "better-npm-run": "0.0.12",
    "chai": "3.5.0",
    "chai-as-promised": "5.3.0",
    "codelyzer": "1.0.0-beta.3",
    "cucumber": "1.3.1",
    "cucumber-tsflow": "1.2.1",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "2.0.0",
    "karma-cli": "1.0.1",
    "karma-coverage": "1.1.1",
    "karma-jasmine": "1.0.2",
    "karma-phantomjs-launcher": "1.0.0",
    "karma-remap-istanbul": "0.2.1",
    "karma-spec-reporter": "0.0.26",
    "lodash": "4.0.1",
    "merge": "^1.2.0",
    "phantomjs-prebuilt": "2.1.7",
    "protractor": "4.0.9",
    "protractor-cucumber-framework": "0.6.0",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "2.0.2",
    "typings": "1.3.3"
  }
}

**Comment by patrickoneill46** [comment]
I just found this repo today and after cloning and installing am also having a typescript error. @samvloeberghs great to see a cucumber acceptance testing implemented in angular 2, by the way.

`[17:01:54] E/launcher - Error: TSError: ⨯ Unable to compile TypeScript
node_modules/@types/jasmine/index.d.ts (39,38): A parameter initializer is only allowed in a function or constructor implementation. (2371)
node_modules/@types/jasmine/index.d.ts (39,46): Cannot find name 'keyof'. (2304)
node_modules/@types/jasmine/index.d.ts (39,52): '=' expected. (1005)
node_modules/@types/jasmine/index.d.ts (41,46): A parameter initializer is only allowed in a function or constructor implementation. (2371)
node_modules/@types/jasmine/index.d.ts (41,56): Cannot find name 'keyof'. (2304)
node_modules/@types/jasmine/index.d.ts (41,62): '=' expected. (1005)
    at getOutput (/Users/patrick.oneill/dev/protractor-gherkin-cucumberjs-angular2/node_modules/ts-node/src/ts-node.ts:210:13)
    at Object.loader (/Users/patrick.oneill/dev/protractor-gherkin-cucumberjs-angular2/node_modules/ts-node/src/ts-node.ts:225:23)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /Users/patrick.oneill/dev/protractor-gherkin-cucumberjs-angular2/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:63:29
    at Array.forEach (native)
    at Object.wrapper (/Users/patrick.oneill/dev/protractor-gherkin-cucumberjs-angular2/node_modules/cucumber/lib/cucumber/cli/support_code_loader.js:62:15)
`

I'm not sure where to start looking for the error in that stack trace.

**Comment by samvloeberghs** [comment]
I'll try to allocate some time to take a look at this..
@DennisJaamann

**Comment by patrickoneill46** [comment]
I had to run the npm scripts `npm run webdriver:update` as well and then it worked. I'm going to take a stab at running the tests in this repo using the angular cli RC

**Comment by DennisJaamann** [comment]
@thirumalai-kc , I created a pull request to fix this issue once and for all external dependencies by storing the exact versions in the package.json

**Comment by samvloeberghs** [comment]
@thirumalai-kc @DennisJaamann merged

**Comment by samvloeberghs** [comment]
@thirumalai-kc can you check?
